---

- name: Generate an cloudinit configuration
  ansible.builtin.include_role:
    name: pimvh.cloud_init
  vars:
    # cloud init is template to temp file, which is removed afterwards
    cloud_init_path: "{{ _temp_cloud_init_config_storage.path }}"

    cloud_init_machine_name: "{{ virtual_machine.name }}"
    cloud_init_ansible_user_passwd_hash: "{{ virtual_machine.ansible_pull.ansible_user_passwd_hash }}"

    # actual cloud init configuration
    cloud_init_userdata: "{{ virtual_machine.cloud_init_userdata }}"
    cloud_init_networkdata: "{{ virtual_machine.cloud_init_networkdata }}"

    # ansible pull configuration
    cloud_init_enable_ansible_pull: "{{ virtual_machine.ansible_pull.enabled | default(false) }}"
    cloud_init_ansible_pull_repo_owner: "{{ virtual_machine.ansible_pull.repo_owner | default('') }}"
    cloud_init_ansible_pull_repo_name: "{{ virtual_machine.ansible_pull.repo_name | default('') }}"
    cloud_init_ansible_pull_playbook_name: "{{ virtual_machine.ansible_pull.playbook_name | default('') }}"
    cloud_init_ansible_pull_deploy_key_name: "{{ virtual_machine.ansible_pull.deploy_key_name | default('') }}"

    # ssh ca configuration
    cloud_init_enable_ssh_ca: "{{ virtual_machine.ssh_ca.enabled | default(false) }}"
    cloud_init_ssh_host_ca_privatekey: "{{ virtual_machine.ssh_ca.host_ca_privatekey | default('') }}"
    cloud_init_ssh_host_ca_privatekey_pass: "{{ virtual_machine.ssh_ca.host_ca_privatekey_pass | default('') }}"
    cloud_init_ssh_host_ca_publickey: "{{ virtual_machine.ssh_ca.host_ca_publickey | default('') }}"
    cloud_init_ssh_user_ca_publickeys: "{{ virtual_machine.ssh_ca.user_ca_publickeys | default([]) }}"
    cloud_init_add_to_known_hosts: "{{ libvirt_cloud_init_add_to_known_hosts }}"

    # whether to reboot the VM on finish
    cloud_init_reboot_on_finish: "{{ libvirt_cloud_init_reboot_on_finish }}"
