---
- name: List available pools
  community.libvirt.virt_pool:
    command: list_pools
  register: current_pools
  become: true

- name: Find correct pool
  ansible.builtin.set_fact:
    vm_pool: "{{ libvirt_pools | get_pool(virtual_machine.pool) }}"

- name: Create pool when not in pools
  community.libvirt.virt_pool:
    command: define
    name: "{{ vm_pool.name }}"
    xml: "{{ vm_pool.xml }}"
  when: not vm_pool.name in current_pools
  become: true
