---
- name: List available networks
  community.libvirt.virt_net:
    command: list_nets
  register: current_networks
  become: true

- name: Create network when not in networks
  community.libvirt.virt_net:
    command: define
    name: "{{ network }}"
    xml: "{{ libvirt_networks[network].xml }}"
    state: active
  when: not network in current_networks
  become: true
  loop: "{{ virtual_machine.networks }}"
  loop_control:
    loop_var: "network"

- name: Ensure that network will be started at boot
  community.libvirt.virt_net:
    autostart: true
    name: "{{ network }}"
  become: true
  loop: "{{ virtual_machine.networks }}"
  loop_control:
    loop_var: "network"
