---
- name: Set known network names
  ansible.builtin.set_fact:
    known_network_names: "{{ libvirt_networks | map(attribute='name') | list }}"

- name: Set known pool names
  ansible.builtin.set_fact:
    known_pool_names: "{{ libvirt_pools | map(attribute='name') | list }}"

- name: Verify that required networks are defined
  ansible.builtin.assert:
    that: "{{ item in known_network_names }}"
    fail_msg: "{{ item }} needs to be set as a network"
    success_msg: "Required variable {{ item }} is defined as a network"
  changed_when: false
  loop: "{{ virtual_machine.networks }}"

- name: Verify that required pools are defined
  ansible.builtin.assert:
    that: "{{ virtual_machine.pool in known_pool_names }}"
    fail_msg: "{{ virtual_machine.pool }} needs to be set as a pool"
    success_msg: "Required variable {{ virtual_machine.pool }} is defined as a pool"
  changed_when: false
  diff: false
