---
- name: Verify that required variables are defined
  ansible.builtin.assert:
    that:
      - "{{ item }} is defined"
      - "{{ item }} | string | length > 0"
      - "{{ item }} != None"
    fail_msg: "{{ item }} needs to be set for the role to work"
    success_msg: "Required variable {{ item }} is defined"
  changed_when: false
  diff: false
  loop:
    - virtual_machine.image.url
    - virtual_machine.image.hashes_url
    - virtual_machine.pool
    - virtual_machine.name
    - virtual_machine.ram
    - virtual_machine.vcpus
    - virtual_machine.disksize
    - virtual_machine.networks
    - virtual_machine.os
    - virtual_machine.cloud_init_userdata
    - virtual_machine.cloud_init_networkdata

- name: Verify that required networks are defined
  ansible.builtin.assert:
    that: "libvirt_networks.{{ item }} is defined"
    fail_msg: "{{ item }} needs to be set as a network"
    success_msg: "Required variable {{ item }} is defined as a network"
  changed_when: false
  loop: "{{ virtual_machine.networks }}"

- name: Verify that required pools are defined
  ansible.builtin.assert:
    that: "{{ virtual_machine.pool in libvirt_pools }}"
    fail_msg: "{{ virtual_machine.pool }} needs to be set as a pool"
    success_msg: "Required variable {{ virtual_machine.pool  }} is defined as a pool"
  changed_when: false
  diff: false
